INSERT INTO `question`(`id`, `question_text`, `type`) VALUES
(1,  '1/36 Ho facilita di prendermi carico di qualsiasi situazione', 'AGGRESSIVE'),
(2,  '2/36 Mi adeguo ai piccolo riti della vita sociale, anche se non li condivido', 'PASSIVE'),
(3,  '3/36 Quando mi trovo a litigare, non altero il volume della voce', 'ASSERTIVE'),
(4,  '4/36 Non ho nessuna difficolta a fissure a lungo una persona negli occhi', 'AGGRESSIVE'),
(5,  '5/36 Mi sentirei perso se improvvisamente mi si chiedesse di affrontare una emergenza', 'PASSIVE'),
(6,  '6/36 Quando mi sento nervosa mi strofino le mani', 'PASSIVE'),
(7,  '7/36 Se la situazione lo richiede non esito ad alzare la voce', 'AGGRESSIVE'),
(8,  '8/36 Per farmi strada nella vita, non uso ne il sarcasmo ne l’ironia', 'ASSERTIVE'),
(9,  '9/36 Penso che ogni persona abbia il diritto a comportarsi come meglio crede', 'ASSERTIVE'),
(10, '10/36 Ho facilita a dire quello che penso anche quando cio contrasta con il punto di vista degli altri', 'AGGRESSIVE'),
(11, '11/36 Anche quando sono nervosa le mani non mi tremano affatto', 'ASSERTIVE'),
(12, '12/36 Sono piuttosto critico nei confronti delle mie azioni', 'PASSIVE'),
(13, '13/36 Ho difficolta a guardare dritto negli occhi la persona con cui sto litigando', 'PASSIVE'),
(14, '14/36 Per sottolineare un punto particolare della mia argomentazione, non ho difficolta a puntare il ditto contro uno dei miei interlocutori', 'AGGRESSIVE'),
(15, '15/36 Sono convinto che tutti dovrebbero comportarsi nei modi richiesti dall’educazione', 'AGGRESSIVE'),
(16, '16/36 Sono tenace ed in genere raggiungo I miei obiettivi, costi quel che costi', 'AGGRESSIVE'),
(17, '17/36 So che mi fa apparire nervosa il tremolio della mia voce quando litigo', 'PASSIVE'),
(18, '18/36 Anche qunado ascolto gli altri sono attento al mio punto di vista', 'ASSERTIVE'),
(19, '19/36 Anche qundo gli altri ottengono da me delle concessioni, grazie all simpatico che mi ispirano, mi assicuro che siano loro a decider dei loro problem', 'ASSERTIVE'),
(20, '20/36 Sono convinto che lasciar trasparire i propri sentimenti sia utile nel creare un buon rapport', 'ASSERTIVE'),
(21, '21/36 Se qualcuno cerca di prendere il sopravvento su di me, gli rispondo per le rime', 'AGGRESSIVE'),
(22, '22/36 Uso il sarcasm per far sapere agli altri quello che penso di loro', 'AGGRESSIVE'),
(23, '23/36 Mi sento a disagio quando gli altri mi criticano', 'PASSIVE'),
(24, '24/36 Quando gli altri si sforzano di farmi dare qualcosa che non mi piace, riesco a trovare un compromesso che soddisfa tutti', 'ASSERTIVE'),
(25, '25/36 Non riesco a capire molte delle critiche che mi vengono rivolte', 'AGGRESSIVE'),
(26, '26/36 Tendo ad affrontare I problemi in modo cauto e democratico, coinvolgono gli altri', 'ASSERTIVE'),
(27, '27/36 Mi imbarazza comunicare agli altri i miei sentimenti e le mie emozioni', 'PASSIVE'),
(28, '28/36 Quando discuto con qualcuno, sono pronto a preferire le sue proposte alle mie', 'PASSIVE'),
(29, '29/36 Se gli altri si trovano in mezzi alle difficolta, e un loro problema', 'AGGRESSIVE'),
(30, '30/36 Ho difficolta a mantenere il mio punto di vista quando entro in contrasto con gli altri', 'PASSIVE'),
(31, '31/36 Ho imparato molto ascoltando gli altri', 'ASSERTIVE'),
(32, '32/36 Mi faccio facilmente intimidire da i prepotenti', 'PASSIVE'),
(33, '33/36 Penso che mostrare agli altri i propri sentimenti sia un segno di debolezza ed e per questo ragione che non lo faccio', 'AGGRESSIVE'),
(34, '34/36 Quando instauro un rapporto con gli altri, facilmente mi trovo a condividere il loro problem', 'PASSIVE'),
(35, '35/36 Trovo che mantenere saldamente il proprio punto di vista, incoraggia l’altro ad accettare un compromesso', 'ASSERTIVE'),
(36, '36/36 Continuo a guardare gli altri, fino a che non mi accorgo che cio li imbarazza', 'ASSERTIVE');
